name: Pre-Commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # install python before running pre-commit
  preCommitValidation:
    name: Pre Commit Validation
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.workspace }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.3"
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.50.3
      # - run: echo ${{ github.workspace }}
      # - run: terraform fmt
      - uses: pre-commit/action@v3.0.1
