name: Pre-Commit

on:
  pull_request:
    branches:
      - main

jobs:
  preCommitValidation:
    name: Pre Commit Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - uses: pre-commit/action@v3.0.1
